version: 1.0.{build}
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: jE+uYnSDVrBExOFkaPPHpJeKfHxVuS+lYvS+8BlcKBTSioz25h+rBq3RxMGl9JBd
  PreReleaseSuffix: alpha
  CoverWith: OpenCover
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
build_script:
- ps: .\build.ps1 -Target AppVeyor
artifacts:
- path: artifacts/packages/*.nupkg
- path: artifacts/coverage/*.xml
- path: artifacts/test-results/*.xml
- path: artifacts/resharper-reports/*.xml
- path: artifacts/resharper-reports/*.html
deploy:
- provider: NuGet
  server: https://www.myget.org/F/alhardy/api/v2/package
  api_key:
    secure: gIAiACgNj+JzXyLLTe3rLxZyrAB9RpC8Lw81xEjdOLXqotprqEwGiFWRipEqkpps
  skip_symbols: true
  symbol_server: https://www.myget.org/F/alhardy/symbol